COLLEGE_REGISTRY = {
    "princeton university": {"coa": 90730, "endowment": "$36.4 Billion"},
    "harvard university": {"coa": 89315, "endowment": "$55.6 Billion"},
    "duke university": {"coa": 92042, "endowment": "$12.3 Billion"},
    "massachusetts institute of technology": {"coa": 90500, "endowment": "$27.3 Billion"},
    "stanford university": {"coa": 91200, "endowment": "$40.7 Billion"},
    "yale university": {"coa": 91800, "endowment": "$44.1 Billion"},
    "university of pennsylvania": {"coa": 92200, "endowment": "$24.8 Billion"},
    "california institute of technology": {"coa": 89500, "endowment": "$4.3 Billion"},
    "brown university": {"coa": 91500, "endowment": "$7.2 Billion"},
    "johns hopkins university": {"coa": 88900, "endowment": "$13.7 Billion"},
    "northwestern university": {"coa": 91200, "endowment": "$15.1 Billion"},
    "columbia university": {"coa": 93100, "endowment": "$15.9 Billion"},
    "cornell university": {"coa": 90200, "endowment": "$11.7 Billion"},
    "university of chicago": {"coa": 91800, "endowment": "$10.6 Billion"},
    "dartmouth college": {"coa": 91600, "endowment": "$8.9 Billion"},
    "vanderbilt university": {"coa": 89900, "endowment": "$10.8 Billion"},
    "rice university": {"coa": 85500, "endowment": "$8.5 Billion"},
    "washington university in st. louis": {"coa": 90100, "endowment": "$13.3 Billion"},
    "university of notre dame": {"coa": 89200, "endowment": "$20.0 Billion"},
    "emory university": {"coa": 88400, "endowment": "$12.0 Billion"},
    "georgetown university": {"coa": 89700, "endowment": "$3.9 Billion"},
    "carnegie mellon university": {"coa": 90400, "endowment": "$4.2 Billion"},
    "new york university": {"coa": 93200, "endowment": "$7.2 Billion"},
    "university of southern california": {"coa": 92500, "endowment": "$9.0 Billion"},
    "tufts university": {"coa": 92100, "endowment": "$2.7 Billion"},
    "boston college": {"coa": 91400, "endowment": "$4.2 Billion"},
    "wake forest university": {"coa": 88200, "endowment": "$2.1 Billion"},
    "university of michigan": {"coa": 76500, "endowment": "$21.2 Billion"},
    "university of virginia": {"coa": 74200, "endowment": "$11.2 Billion"},
    "university of north carolina at chapel hill": {"coa": 61800, "endowment": "$6.2 Billion"},
    "university of california, berkeley": {"coa": 78500, "endowment": "$20.1 Billion"},
    "university of california, los angeles": {"coa": 77200, "endowment": "$20.1 Billion"},
    "university of california, san diego": {"coa": 75900, "endowment": "$20.1 Billion"},
    "university of california, irvine": {"coa": 74800, "endowment": "$20.1 Billion"},
    "university of california, santa barbara": {"coa": 76100, "endowment": "$20.1 Billion"},
    "university of florida": {"coa": 48500, "endowment": "$2.5 Billion"},
    "university of texas at austin": {"coa": 59200, "endowment": "$6.4 Billion"},
    "georgia institute of technology": {"coa": 54500, "endowment": "$3.2 Billion"},
    "university of illinois urbana-champaign": {"coa": 61200, "endowment": "$2.8 Billion"},
    "university of wisconsin-madison": {"coa": 58400, "endowment": "$4.9 Billion"}
}